// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string   `json:"id"`
	User      *User    `json:"user"`
	Req       *Request `json:"req"`
	Text      string   `json:"text"`
	CreatedTs string   `json:"created_ts"`
}

type Interest struct {
	ID           string   `json:"id"`
	User         *User    `json:"user"`
	AcceptedUser *User    `json:"accepted_user"`
	Request      *Request `json:"request"`
	Description  *string  `json:"description"`
	Accepted     bool     `json:"accepted"`
	CreatedTs    *string  `json:"created_ts"`
	AcceptedTs   *string  `json:"accepted_ts"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewComment struct {
	Text string `json:"text"`
	Req  string `json:"req"`
}

type NewInterest struct {
	User        string  `json:"user"`
	Req         string  `json:"req"`
	Description *string `json:"description"`
}

type NewRequest struct {
	Title    string `json:"title"`
	Location string `json:"location"`
	Workout  string `json:"workout"`
	Time     string `json:"time"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Age      int    `json:"age"`
	Gender   string `json:"gender"`
	Level    string `json:"level"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Request struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Location  string  `json:"location"`
	Workout   string  `json:"workout"`
	Status    *string `json:"status"`
	Time      *string `json:"time"`
	User      *User   `json:"user"`
	CreatedTs *string `json:"created_ts"`
}

type RequestByID struct {
	ID int `json:"id"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Age      int    `json:"age"`
	Gender   string `json:"gender"`
	Level    string `json:"level"`
}
